
services:
###> doctrine/doctrine-bundle ###
  mysql:
    env_file:
      - ./.env.local
    ports:
      - "3306"
    volumes:
      - ./var/db_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
